### ISSUE TITLE
Add heapsort implementation

### ISSUE THREAD

**Issue by jonasclauss** [cbl/algorithm-analyzer#22]

**Comment by herrmanno** [comment]
@sachsenjonas Didn't notice that you already assigned this issue to yourself. In the meantime, I've prepared some basic structure and functions around min/max heaps in general. If you aren't near the finish line of closing this issue yourself, maybe have a look inside the linked PR #23 and see if you can build your work upon that.

**Comment by jonasclauss** [comment]
@herrmanno I've made a PR #32 as well. You can have a look as well.
