### ISSUE TITLE
Add deepsearch (Tiefensuche) implementation

### ISSUE THREAD

**Issue by cbl** [cbl/algorithm-analyzer#29]

**Comment by jonasclauss** [comment]
I don't know if this issue is still to do but as far as i can see, we've already implemented the deepsearch succesfully.
![Bildschirmfoto 2021-07-25 um 12 33 40](https://user-images.githubusercontent.com/73591771/126896109-f8dcd9ad-6259-4f82-976f-a4e66b562281.png)

**Comment by jonasclauss** [comment]
The output exists of just 4 nodes even if you have 5 or more nodes.

**Comment by cbl** [comment]
Turns out, the problem could be solved by increasing the `size`.
