### ISSUE TITLE
Add binary search implementation

### ISSUE THREAD

**Issue by jonasclauss** [cbl/algorithm-analyzer#36]
![Bildschirmfoto 2021-07-25 um 14 38 33](https://user-images.githubusercontent.com/73591771/126899225-71ec17f7-cb02-4b8c-801b-be78386d148b.png)

**Comment by JojoMee** [comment]
Unfortunately I can't assign this issue to myself so I wanted to note that I'm currently working on it: https://github.com/JojoMee/algorithm-analyzer/tree/feat/binary-search

**Comment by cbl** [comment]
Check your mails, I just sent you an invite. 😉
